# Generated by Django 6.0.2 on 2026-08-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('data_pedido', models.DateField()),
                ('fk_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pessoa.pessoa')),
                ('produtos', models.ManyToManyField(related_name='pedidos', through='pedidos.Pedido_Produto', to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedidos.pedidos'),
        ),
        migrations.AlterUniqueTogether(
            name='pedido_produto',
            unique_together={('fk_pedido', 'fk_produto')},
        ),
    ]
