# Generated by Django 6.0.2 on 2026-08-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fk_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pessoa.pessoa'),
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedidos.pedidos'),
        ),
        migrations.AlterUniqueTogether(
            name='pedido_produto',
            unique_together={('fk_pedido', 'fk_produto')},
        ),
    ]
