# Generated by Django 6.0.2 on 2026-08-09 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '4 - Cobertura',
                'verbose_name_plural': '4 - Cobertura',
            },
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('capacidade_maxima_bolas', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '1 - Embalagem',
                'verbose_name_plural': '1 - Embalagem',
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '3 - Sabor',
                'verbose_name_plural': '3 - Sabor',
            },
        ),
        migrations.CreateModel(
            name='TipoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '2 - TipoSabor',
                'verbose_name_plural': '2 - TipoSabor',
            },
        ),
        migrations.CreateModel(
            name='MontaPote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, null=True)),
                ('coberturas', models.ManyToManyField(blank=True, to='pessoa.cobertura')),
                ('embalagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potes', to='pessoa.embalagem')),
            ],
            options={
                'verbose_name': 'B - MontaPote',
                'verbose_name_plural': 'B - MontaPote',
            },
        ),
        migrations.CreateModel(
            name='SacolaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potes', models.ManyToManyField(to='pessoa.montapote')),
            ],
            options={
                'verbose_name': 'C - SacolaItens',
                'verbose_name_plural': 'C - SacolaItens',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('itens_da_sacola', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sacolaitens')),
            ],
            options={
                'verbose_name': 'D - Pedido',
                'verbose_name_plural': 'D - Pedido',
            },
        ),
        migrations.CreateModel(
            name='SelSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bolas', models.PositiveIntegerField(default=1)),
                ('pote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabores_selecionados', to='pessoa.montapote')),
                ('sabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selecoes', to='pessoa.sabor')),
            ],
            options={
                'verbose_name': 'A - SelSabor',
                'verbose_name_plural': 'A - SelSabor',
            },
        ),
        migrations.AddField(
            model_name='sabor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='pessoa.tiposabor'),
        ),
    ]
