# Generated by Django 6.0.2 on 2026-08-09 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='montapote',
            name='coberturas',
        ),
        migrations.RemoveField(
            model_name='montapote',
            name='embalagem',
        ),
        migrations.RemoveField(
            model_name='sacolaitens',
            name='potes',
        ),
        migrations.RemoveField(
            model_name='selsabor',
            name='pote',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='selsabor',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens_da_sacola',
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(default='Cartão', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='endereco', serialize=False, to='pessoa.pessoa')),
                ('cidade', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('rua', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pessoa.pessoa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.IntegerField(default=1)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pessoa.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_item', to='pessoa.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedidos', through='pessoa.PedidoProduto', to='pessoa.produto'),
        ),
        migrations.DeleteModel(
            name='Cobertura',
        ),
        migrations.DeleteModel(
            name='Embalagem',
        ),
        migrations.DeleteModel(
            name='MontaPote',
        ),
        migrations.DeleteModel(
            name='TipoSabor',
        ),
        migrations.DeleteModel(
            name='Sabor',
        ),
        migrations.DeleteModel(
            name='SelSabor',
        ),
        migrations.DeleteModel(
            name='SacolaItens',
        ),
    ]
